name: Publish

on:
  push:
    branches:
      - main
      - alpha

jobs:
  publish-packages:
    name: Publish packages to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: '0'
          token: ${{ secrets.GH_TOKEN }}

      - name: Set node version
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --immutable


      - name: Cache Example dependencies
        id: cache-example
        uses: actions/cache@v3
        with:
          path: 'example/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('example/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('example/yarn.lock') }}
            ${{ runner.os }}-node-

      - name: Install Example dependencies
        if: steps.cache-example.outputs.cache-hit != 'true'
        working-directory: example
        run: yarn install --immutable

      - name: Cache Doc dependencies
        id: cache-doc
        uses: actions/cache@v3
        with:
          path: 'doc/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('doc/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('doc/yarn.lock') }}
            ${{ runner.os }}-node-

      - name: Install Doc dependencies
        if: steps.cache-doc.outputs.cache-hit != 'true'
        working-directory: doc
        run: yarn install --immutable

      - name: Build Docs
        working-directory: doc
        run: yarn build

      - name: Deploy Docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        working-directory: doc
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com

      - name: Build
        run: yarn build

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          branches: |
            [
              'main',
              {
                name: 'alpha',
                prerelease: true
              }
            ]