name: Static Check

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  check:
    name: ESLint & Typescript & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/cli.tgz') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/cli.tgz') }}
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn up cli@file:./cli.tgz && yarn install --immutable

      - name: Check Lint
        run: yarn lint

      - name: Check TypeScript
        run: yarn check:type

      - name: Test
        run: yarn test